version: '3'
services:
  db:
    image: postgres:14
    restart: always
    container_name: sfd_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: sfd
    ports:
      - "5432:5432"
    volumes:
      - sfd_data:/var/lib/postgresql/data
  test-db:
    image: postgres:14
    restart: always
    container_name: sfd_test_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: sfd_test
    ports:
      - "5433:5432"
    volumes:
      - sfd_test_data:/var/lib/postgresql/data
volumes:
  sfd_data:
  sfd_test_data: