version: '3'
services:
  adminer:
    image: adminer
    restart: always
    container_name: sfd_adminer
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: pgsql
  db:
    image: postgres:14
    restart: always
    container_name: sfd_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: sfd
    ports:
      - "5432:5432"
    volumes:
      - sfd_data:/var/lib/postgresql/data

volumes:
  sfd_data: