#get own user

GET http://localhost:3333/users/me HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjQsImVtYWlsIjoidGVzdDFAdGVzdC50ZXN0IiwiaWF0IjoxNzEwMDc5NTkxLCJleHAiOjE3MTAwODA0OTF9.o44F19f1Jv7VRGuvbsn30ghIzwKarrlPXpVoydTTyeo

###

#get user by id

GET http://localhost:3333/users/7 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjgsImVtYWlsIjoidGVzdDJAdGVzdC50ZXN0IiwiaWF0IjoxNzEwMTQ5ODcwLCJleHAiOjE3MTAxNTA3NzB9.kKWa7oPHCfe9VfdpD2ur3XLzKSGOYMXc3892UIkY704

###

#update user

PATCH http://localhost:3333/users HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjQsImVtYWlsIjoidGVzdDFAdGVzdC50ZXN0IiwiaWF0IjoxNzEwMDkxMzQxLCJleHAiOjE3MTAwOTIyNDF9.0-9jGENKNOir1kBxlxxTflpzFCLC8wiuLr8UVY2TMjc

{
  "fullName": "New Name"
}

###

#upload avatar

POST http://localhost:3333/users/upload HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjgsImVtYWlsIjoidGVzdDJAdGVzdC50ZXN0IiwiaWF0IjoxNzEwMTYyNDIwLCJleHAiOjE3MTAxNjMzMjB9.vLwFDDnHTEyLUF8L3OzXuBbMpbwzn41VsY9SWz4LefU

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="avatar.jpg"
Content-Type: image/jpeg

< /Users/user/Desktop/THP/projet final/server/api/img/avatar.jpeg
------WebKitFormBoundary7MA4YWxkTrZu0gW--